### ISSUE TITLE
能否同步 2 个私有库

### ISSUE THREAD

**Issue by Leader755** [gyx8899/blog#19]
能够将 github 的私库同步到 gitee 私库，我现在一直是失败的。不知道是不是我配置问题还是，报错如下。
fatal: could not read Username for 'https://github.com': No such device or address',请问是由于私有库的问题吗。

![image](https://user-images.githubusercontent.com/37180494/116778683-ef892380-aaa5-11eb-8fc9-b618e96b1352.png)
![image](https://user-images.githubusercontent.com/37180494/116778691-016ac680-aaa6-11eb-9014-86c82e73034f.png)

**Comment by gyx8899** [comment]
@Leader755 ，是私有库的原因，Github 私有库还不支持使用`Github Action`，将来会支持，详情见如下链接：
<https://github.com/github/roadmap/projects/1#card-42486648> Github public roadmap
[Actions: Use actions from private and internal repositories](https://github.com/github/roadmap/issues/74)

**Comment by Leader755** [comment]
好的
